# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/users_database
spring.datasource.username=shop_user
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public
# Logging
logging.level.root=DEBUG
logging.level.org.springframework.security=DEBUG
logging.file.name=logs/application.log
logging.file.max-history=1 # Keeps only the latest log file (overwrite every time)